### ISSUE TITLE
Having Issues with Configuration

### ISSUE THREAD

**Issue by colb1232** [edwork/homeassistant-peloton-sensor#100]
Everything’s been working with the integration until today and I got this error message:

2024-10-23 21:12:31.553 ERROR (MainThread) [custom_components.peloton.config_flow] Unexpected exception
Traceback (most recent call last):
File "/config/custom_components/peloton/config_flow.py", line 115, in async_step_user
api = await async_validate_input(self.hass, user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/peloton/config_flow.py", line 41, in async_validate_input
await hass.async_add_executor_job(api.GetMe)
File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pylotoncycle/pylotoncycle.py", line 51, in GetMe
self.username = resp["username"]
~~~~^^^^^^^^^^^^
KeyError: 'username'

**Comment by darrenmcuk** [comment]
I am getting the exact same thing

**Comment by edwork** [comment]
I was able to replicate this on HomeAssistant 2024.10.3, but after upgrading to 2024.10.4 I can no longer replicate the issue. Using the `api_debug.py` script in the root of this repo the json object I receive seems to be alright, so I think this may just be an issue with 2024.10.3 specifically.  

I'll keep trying to replicate the issue on 2024.10.4 just in case.
