### ISSUE TITLE
Some structures changed after api update?

### ISSUE THREAD

**Issue by dimab0** [edwork/homeassistant-peloton-sensor#13]
Seeing the below errors upon logging in now.
`
2021-06-23 11:38:48 ERROR (MainThread) [homeassistant.components.sensor] peloton: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 358, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
await task
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/peloton/sensor.py", line 80, in update
conn = pylotoncycle.PylotonCycle(self.user, self.password)
File "/config/custom_components/peloton/pylotoncycle/pylotoncycle.py", line 31, in __init__
self.login(username, password)
File "/config/custom_components/peloton/pylotoncycle/pylotoncycle.py", line 52, in login
self.total_workouts = resp['user_data']['total_workouts']
KeyError: 'user_data'
`

**Comment by edwork** [comment]
Hello!

Thanks for filing this. I'm working on trying to reproduce this using version `0.5.1` of the `pylotoncycle` library, but so far I'm returning the object successfully with no changes. It appears this problem is with the pylotoncycle library vs the implementation we're using here. 

Just to rule out some outliers do you have a very high number of rides on your profile?

To further rule out some issues you can try running the `api_debug.py` script in the root of this repository and see if you are successfully return a long object string. 

Thanks, I'll keep working things out,
Ed

**Comment by dimab0** [comment]
I'm running hassio so struggling to run a standalone python script. Apparently it is nothing trivial. I do not have very many rides on my profile...
I did confirm my login info is still correct and works. I don't know what would have changed. I may try to use this library and debug on a different computer later that can actually run a py script.

**Comment by edwork** [comment]
Hello,  

Please update to `0.5.2` either via HACS or a [direct link to the release](https://github.com/edwork/homeassistant-peloton-sensor/releases/tag/0.5.2).  

Please let me know if this fixes your issue.  

Cheers!

**Comment by dimab0** [comment]
New error at least!

`
peloton: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 358, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/peloton/sensor.py", line 81, in update
    workouts = conn.GetRecentWorkouts(1)
  File "/usr/local/lib/python3.8/site-packages/pylotoncycle/pylotoncycle.py", line 111, in GetRecentWorkouts
    resp_summary = self.GetWorkoutSummaryById(workout_id)
  File "/usr/local/lib/python3.8/site-packages/pylotoncycle/pylotoncycle.py", line 132, in GetWorkoutSummaryById
    resp = self.GetUrl(url)
  File "/usr/local/lib/python3.8/site-packages/pylotoncycle/pylotoncycle.py", line 62, in GetUrl
    resp = self.s.get(url, timeout=10).json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 2 column 5 (char 5)
`

**Comment by edwork** [comment]
My mistake, [please update to 0.5.3](https://github.com/edwork/homeassistant-peloton-sensor/releases/tag/0.5.3). The version bump made it to the name in the manifest file but not the requirements field.

**Comment by dimab0** [comment]
Looks good now.
