### ISSUE TITLE
KeyError: 'ride'

### ISSUE THREAD

**Issue by neildsb** [edwork/homeassistant-peloton-sensor#49]
Just popped up today?

Home Assistant 2022.9.4
Supervisor 2022.08.6
Operating System 9.0
Frontend 20220907.2 - latest

This error originated from a custom integration.

Logger: custom_components.peloton
Source: custom_components/peloton/__init__.py:58
Integration: Peloton (documentation, issues)
First occurred: 4:03:59 pm (3 occurrences)
Last logged: 4:04:19 pm

Unexpected error fetching peloton data: 'ride'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/peloton/__init__.py", line 58, in async_update_data
    workouts = await hass.async_add_executor_job(api.GetRecentWorkouts, 1)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pylotoncycle/pylotoncycle.py", line 114, in GetRecentWorkouts
    if 'instructor_id' in resp_workout['ride']:
KeyError: 'ride'

![image](https://user-images.githubusercontent.com/91122872/190440186-ccd0d0e1-6e90-48e1-a8dd-33a9e1f49195.png)

**Comment by neildsb** [comment]
its working again, not sure if its a head end problem, thanks again for the great integration 

![image](https://user-images.githubusercontent.com/91122872/190442145-2759519f-eab2-4c09-b5b0-c2b11923bd08.png)
