### ISSUE TITLE
This entity is no longer being provided by the peloton integration.

### ISSUE THREAD

**Issue by neildsb** [edwork/homeassistant-peloton-sensor#54]
Hi Ed, not sure if this a problem with my setup, but the binary sensor for 'workout type' has stopped working with 2023.1.0

I will keep debugging.....

      peloton_workout:
        icon_template: mdi:shoe-sneaker
        friendly_name: "Peloton Workout"
        value_template: >
          {{ state_attr('binary_sensor.neil_on_peloton_workout', "Workout Type") }}

binary_sensor.neil_on_peloton_workout

This entity is no longer being provided by the peloton integration. If the entity is no longer in use, delete it in settings.

Home Assistant 2023.1.0
Supervisor 2022.12.1
Operating System 9.4
Frontend 20221213.1 - latest

![image](https://user-images.githubusercontent.com/91122872/210873543-f44c8f66-0b5d-4a4a-802e-f2eb22cafa31.png)

![image](https://user-images.githubusercontent.com/91122872/210873674-c5c435db-8ee4-43be-b4a1-b48ae8133dc5.png)

from a tread workout
![image](https://user-images.githubusercontent.com/91122872/210874912-586b4cff-8329-4b45-a2cf-9415510cbe3d.png)

![image](https://user-images.githubusercontent.com/91122872/210875802-008b2419-67ea-4c3e-b57f-fb74633fc59e.png)

**Comment by neildsb** [comment]
thanks Ed, sorry, I had a typo, I also am running 2023.1.0, I updated 13hrs ago ie today :-)

if it helps, I have noticed the following 
pylotoncycle 0.6.0
![image](https://user-images.githubusercontent.com/91122872/210877464-a5c05b43-0edd-41b1-969f-94b2025e98ee.png)

**Comment by neildsb** [comment]
i have some logs also - 


Logger: homeassistant.components.binary_sensor
Source: components/sensor/__init__.py:901
Integration: Binary Sensor (documentation, issues)
First occurred: 7:34:08 pm (1 occurrences)
Last logged: 7:34:08 pm

peloton: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 503, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 729, in async_device_update
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 392, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 175, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 82, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 201, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 316, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 121, in async_update_listeners
    update_callback()
  File "/config/custom_components/peloton/sensor.py", line 120, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 556, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 562, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 901, in state
    raise ValueError(
ValueError: Sensor sensor.neil_on_peloton_end_time has a state class and thus indicating it has a numeric value; however, it has the non-numeric device class: timestamp

**Comment by neildsb** [comment]
I did a quick restore and the sensor is available in 2022.12.9, upgraded to 2023.1.0 again and it's still available? really odd, I did try and restart HA during a workout, I guess it got stuck somewhere. I think its sorted

**Comment by edwork** [comment]
I was able to replicate it, based on your log output I think i can fix it shortly. My sensor was file while inactive but never triggered to on during a ride.

**Comment by edwork** [comment]
Should be fixed now with [Release 0.8.2](https://github.com/edwork/homeassistant-peloton-sensor/releases/tag/0.8.2)

HomeAssistant as of 2023.1.x does not accept a NoneType for a Timestamp value. This condition happens during ANY type of workout - End Time has no value returned from Peloton since it never happened. HomeAssistant (as I understand, please prove me wrong) for sensors with the Timestamp value cannot return a non-timestamp value so it needs to be set to _something_. 

So now during a ride End Time = Start Time, until the end of the ride. For now this seems like the best option but I'm up for suggestions. Please install the update and restart your instance and you should be all set!

**Comment by neildsb** [comment]
Ur a star thanks, will give it a try!

**Comment by neildsb** [comment]
works as before, thanks again
