### ISSUE TITLE
Lots of log errors lately

### ISSUE THREAD

**Issue by mikesalz** [edwork/homeassistant-peloton-sensor#7]
Hey @edwork!  I hope you're doing well.  I'm not sure if this is something on my end, on Peloton's end, or within the integration.  But I have been receiving a lot of these errors lately.  Any ideas?

```
Logger: homeassistant.helpers.entity
Source: custom_components/peloton/sensor.py:80
First occurred: 10:12:09 AM (186 occurrences)
Last logged: 10:58:10 AM

Update for sensor.peloton_xxx fails
Update for sensor.peloton_yyy fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 277, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 473, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/peloton/sensor.py", line 80, in update
    conn = pylotoncycle.PylotonCycle(self.user, self.password)
  File "/usr/local/lib/python3.8/site-packages/pylotoncycle/pylotoncycle.py", line 31, in __init__
    self.login(username, password)
  File "/usr/local/lib/python3.8/site-packages/pylotoncycle/pylotoncycle.py", line 52, in login
    self.total_workouts = resp['user_data']['total_workouts']
KeyError: 'user_data'
```

**Comment by edwork** [comment]
Hello! 

Thanks for using the sensor! I've had my HASS instance on AutoPilot and didn't notice that I'm receiving the same errors. 

Let me see what I can dig up. 

Thanks!  
Ed

**Comment by aetchells55** [comment]
I'm seeing similar errors. Just seemed to start this morning for me.

**Comment by m3obsessed** [comment]
I had the same issue until this morning.  The error is gone after I restarted HA.  No clue what caused the error.

**Comment by aetchells55** [comment]
Yeah, they vanished last night for me. Maybe it was on Peloton's side but no issues were reported on https://status.onepeloton.com/

**Comment by mikesalz** [comment]
The error has stopped for me as well.  I will close the issue.
