### ISSUE TITLE
Error after reinstall

### ISSUE THREAD

**Issue by Cassock** [edwork/homeassistant-peloton-sensor#83]
I'm refreshing some of my Home Assistant tabs and ran into this error after removing and then re-adding the Peloton integration via HACS:
![image](https://github.com/edwork/homeassistant-peloton-sensor/assets/15901832/def5c4fc-8eea-4477-a8a7-221536a0119a)
with this accompanying entry in the logs:
```Logger: aiohttp.server
Source: requirements.py:275
First occurred: 8:49:40 AM (2 occurrences)
Last logged: 8:49:56 AM

Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/lib/python3.10/site-packages/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/lib/python3.10/site-packages/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/lib/python3.10/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/lib/python3.10/site-packages/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/lib/python3.10/site-packages/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/lib/python3.10/site-packages/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/lib/python3.10/site-packages/homeassistant/components/config/config_entries.py", line 148, in post
    return await super().post(request)
  File "/usr/lib/python3.10/site-packages/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/lib/python3.10/site-packages/homeassistant/config_entries.py", line 845, in async_init
    flow, result = await task
  File "/usr/lib/python3.10/site-packages/homeassistant/config_entries.py", line 863, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/lib/python3.10/site-packages/homeassistant/config_entries.py", line 962, in async_create_flow
    await _load_integration(self.hass, handler_key, self._hass_config)
  File "/usr/lib/python3.10/site-packages/homeassistant/config_entries.py", line 2026, in _load_integration
    await async_process_deps_reqs(hass, hass_config, integration)
  File "/usr/lib/python3.10/site-packages/homeassistant/setup.py", line 389, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/lib/python3.10/site-packages/homeassistant/requirements.py", line 52, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
  File "/usr/lib/python3.10/site-packages/homeassistant/requirements.py", line 171, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/lib/python3.10/site-packages/homeassistant/requirements.py", line 186, in _async_process_integration
    await self.async_process_requirements(
  File "/usr/lib/python3.10/site-packages/homeassistant/requirements.py", line 246, in async_process_requirements
    self._raise_for_failed_requirements(name, missing)
  File "/usr/lib/python3.10/site-packages/homeassistant/requirements.py", line 275, in _raise_for_failed_requirements
    raise RequirementsNotFound(integration, [req])
homeassistant.requirements.RequirementsNotFound: Requirements for peloton not found: ['git+https://github.com/RobertD502/pylotoncycle@dev#pylotoncycle==0.6.0.1'].```

**Comment by edwork** [comment]
Hello,

I'm looking into this - at a glance it seems like HomeAssistant isn't re-downloading the custom library when initializing the integration. 

Can you try:
- Removing the integration from HomeAssistant's UI
- Uninstalling from HACS
- Restarting HomeAssistant
- Reinstalling in HACS
- Reconfigure the integration from the UI

**Comment by Cassock** [comment]
Same 500 error as before, but I just noticed another entry in the log:
```Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 11:03:34 AM (3 occurrences)
Last logged: 11:03:37 AM

Unable to install package git+https://github.com/RobertD502/pylotoncycle@dev#pylotoncycle==0.6.0.1: ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git version ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH? WARNING: You are using pip version 22.0.4; however, version 23.1.2 is available. You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.```

**Comment by DatCFC** [comment]
Same error for me as well

`Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 9:08:53 AM (3 occurrences)
Last logged: 9:08:57 AM

Unable to install package git+https://github.com/RobertD502/pylotoncycle@dev#pylotoncycle==0.6.0.1: WARNING: Ignoring invalid distribution -ettytable (/lsiopy/lib/python3.11/site-packages) WARNING: Ignoring invalid distribution -rettytable (/lsiopy/lib/python3.11/site-packages) WARNING: Ignoring invalid distribution - (/lsiopy/lib/python3.11/site-packages) WARNING: Ignoring invalid distribution -ettytable (/lsiopy/lib/python3.11/site-packages) WARNING: Ignoring invalid distribution -rettytable (/lsiopy/lib/python3.11/site-packages) WARNING: Ignoring invalid distribution - (/lsiopy/lib/python3.11/site-packages) ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git version ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH? WARNING: Ignoring invalid distribution -ettytable (/lsiopy/lib/python3.11/site-packages) WARNING: Ignoring invalid distribution -rettytable (/lsiopy/lib/python3.11/site-packages) WARNING: Ignoring invalid distribution - (/lsiopy/lib/python3.11/site-packages) WARNING: Ignoring invalid distribution -ettytable (/lsiopy/lib/python3.11/site-packages) WARNING: Ignoring invalid distribution -rettytable (/lsiopy/lib/python3.11/site-packages) WARNING: Ignoring invalid distribution - (/lsiopy/lib/python3.11/site-packages) WARNING: Ignoring invalid distribution -ettytable (/lsiopy/lib/python3.11/site-packages) WARNING: Ignoring invalid distribution -rettytable (/lsiopy/lib/python3.11/site-packages) WARNING: Ignoring invalid distribution - (/lsiopy/lib/python3.11/site-packages) WARNING: You are using pip version 22.0.4; however, version 23.1.2 is available. You should consider upgrading via the '/lsiopy/bin/python3 -m pip install --upgrade pip' command.`
