### ISSUE TITLE
Entities have become unavailable

### ISSUE THREAD

**Issue by hollowpnt92** [edwork/homeassistant-peloton-sensor#88]
My integration was working fine up until at a day ago when the integration failed. 

I have tried removing and readding through HACS. 

See log below. 

```
2023-07-10 14:04:49.916 ERROR (MainThread) [custom_components.peloton] Unexpected error fetching peloton data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 242, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/peloton/__init__.py", line 79, in async_update_data
    "quant_data": compile_quant_data(
                  ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/peloton/__init__.py", line 278, in compile_quant_data
    if isinstance((value := metric.get("values")[len(metric.get("values"))-1]), int)
                            ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by edwork** [comment]
Following up with all out of range errors with additional exception logic in issue #89
